export const RECEIVE_ME = 'RECEIVE_ME';
export const RECEIVE_PEOPLE = 'RECEIVE_PEOPLE';
export const SHOW_EMAIL_CHARACTER_FREQUENCY = 'SHOW_EMAIL_CHARACTER_FREQUENCY';
export const HIDE_EMAIL_CHARACTER_FREQUENCY = 'HIDE_EMAIL_CHARACTER_FREQUENCY';
export const TOGGLE_EMAIL_CHARACTER_FREQUENCY = 'TOGGLE_EMAIL_CHARACTER_FREQUENCY';
export const SHOW_POSSIBLE_DUPLICATES = 'SHOW_POSSIBLE_DUPLICATES';
export const HIDE_POSSIBLE_DUPLICATES = 'HIDE_POSSIBLE_DUPLICATES';
export const TOGGLE_POSSIBLE_DUPLICATES = 'TOGGLE_POSSIBLE_DUPLICATES';